# Generated by Django 4.2.1 on 2023-05-12 04:32

from django.db import migrations, models


def load_data_from_sql(apps, schema_editor):
    # Read the SQL file and execute its contents
    with open('/xyz_sales_db.sql', 'r') as f:
        sql_statements = f.read()
        schema_editor.connection.execute(sql_statements)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=20)),
                ('order_date', models.DateField()),
                ('customer_id', models.CharField(max_length=10)),
                ('sub_category', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=10)),
                ('sales', models.FloatField()),
            ],
        ),
    ]
